extends Node

@warning_ignore("unused_signal")
signal phase_changed(old_phase: int, new_phase: int)
@warning_ignore("unused_signal")
signal day_started(day: int)
@warning_ignore("unused_signal")
signal night_started(day: int)
@warning_ignore("unused_signal")
signal night_cleared(day: int)
@warning_ignore("unused_signal")
signal run_ended(win: bool)

@warning_ignore("unused_signal")
signal action_points_changed(value: int)
@warning_ignore("unused_signal")
signal prestige_changed(value: int)
@warning_ignore("unused_signal")
signal materials_changed(wood: int, stone: int, mana: int)
@warning_ignore("unused_signal")
signal core_hp_changed(current: int, max_value: int)
@warning_ignore("unused_signal")
signal deploy_limit_changed(current: int, max_value: int)
@warning_ignore("unused_signal")
signal shop_stock_changed(stock_slots: Array[Dictionary])
@warning_ignore("unused_signal")
signal shop_action_result(action: StringName, result: Dictionary)
@warning_ignore("unused_signal")
signal buffs_changed(buff_ids: Array[StringName])

@warning_ignore("unused_signal")
signal request_explore(cell: Vector2i)
@warning_ignore("unused_signal")
signal request_build(cell: Vector2i, building_id: StringName)
@warning_ignore("unused_signal")
signal request_toggle_building(building_runtime_id: int)
@warning_ignore("unused_signal")
signal request_interact_event(cell: Vector2i)
@warning_ignore("unused_signal")
signal request_start_night()
@warning_ignore("unused_signal")
signal request_buy_shop_slot(slot_index: int)
@warning_ignore("unused_signal")
signal request_refresh_shop()
@warning_ignore("unused_signal")
signal blessing_chosen(buff_id: StringName)

@warning_ignore("unused_signal")
signal owned_operators_changed(operators: Array[Dictionary])
@warning_ignore("unused_signal")
signal owned_units_changed(unit_ids: Array[StringName])
@warning_ignore("unused_signal")
signal map_cell_clicked(cell: Vector2i)

@warning_ignore("unused_signal")
signal map_cell_hovered(cell: Vector2i)

@warning_ignore("unused_signal")
signal right_click_tapped()

@warning_ignore("unused_signal")
signal fog_revealed(cells: Array[Vector2i])
@warning_ignore("unused_signal")
signal building_placed(building_runtime_id: int, building_id: StringName, cell: Vector2i)
@warning_ignore("unused_signal")
signal building_destroyed(building_runtime_id: int, building_id: StringName, cell: Vector2i)
@warning_ignore("unused_signal")
signal building_state_changed(building_runtime_id: int, building_id: StringName, enabled: bool)
@warning_ignore("unused_signal")
signal build_action_result(building_id: StringName, cell: Vector2i, result: Dictionary)
@warning_ignore("unused_signal")
signal resource_collected(cell: Vector2i, resource_type: StringName, amount: int)
@warning_ignore("unused_signal")
signal path_grid_changed()
@warning_ignore("unused_signal")
signal unit_deployed(unit_runtime_id: int, operator_key: StringName, unit_id: StringName, cell: Vector2i)
@warning_ignore("unused_signal")
signal unit_removed(unit_runtime_id: int, reason: int)
@warning_ignore("unused_signal")
signal unit_skill_cast(unit_runtime_id: int, operator_key: StringName, unit_id: StringName)
@warning_ignore("unused_signal")
signal enemy_spawned(enemy_runtime_id: int, enemy_id: StringName, cell: Vector2i)
@warning_ignore("unused_signal")
signal enemy_died(enemy_runtime_id: int, enemy_id: StringName)
@warning_ignore("unused_signal")
signal random_event_triggered(event_id: StringName, cell: Vector2i)
@warning_ignore("unused_signal")
signal blessing_choices_ready(choice_ids: Array[StringName])
@warning_ignore("unused_signal")
signal audio_cue_requested(cue_key: StringName)
@warning_ignore("unused_signal")
signal core_destroyed()
